// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/deadcheat/goblet/generator (interfaces: UseCase,RegexpRepository,PathMatcherRepository)

// Package mock is a generated GoMock package.
package mock

import (
	generator "github.com/deadcheat/goblet/generator"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// LoadFiles mocks base method
func (m *MockUseCase) LoadFiles(arg0, arg1 []string) (*generator.Entity, error) {
	ret := m.ctrl.Call(m, "LoadFiles", arg0, arg1)
	ret0, _ := ret[0].(*generator.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadFiles indicates an expected call of LoadFiles
func (mr *MockUseCaseMockRecorder) LoadFiles(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFiles", reflect.TypeOf((*MockUseCase)(nil).LoadFiles), arg0, arg1)
}

// MockRegexpRepository is a mock of RegexpRepository interface
type MockRegexpRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRegexpRepositoryMockRecorder
}

// MockRegexpRepositoryMockRecorder is the mock recorder for MockRegexpRepository
type MockRegexpRepositoryMockRecorder struct {
	mock *MockRegexpRepository
}

// NewMockRegexpRepository creates a new mock instance
func NewMockRegexpRepository(ctrl *gomock.Controller) *MockRegexpRepository {
	mock := &MockRegexpRepository{ctrl: ctrl}
	mock.recorder = &MockRegexpRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRegexpRepository) EXPECT() *MockRegexpRepositoryMockRecorder {
	return m.recorder
}

// CompilePatterns mocks base method
func (m *MockRegexpRepository) CompilePatterns(arg0 []string) error {
	ret := m.ctrl.Call(m, "CompilePatterns", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompilePatterns indicates an expected call of CompilePatterns
func (mr *MockRegexpRepositoryMockRecorder) CompilePatterns(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompilePatterns", reflect.TypeOf((*MockRegexpRepository)(nil).CompilePatterns), arg0)
}

// MatchAny mocks base method
func (m *MockRegexpRepository) MatchAny(arg0 string) bool {
	ret := m.ctrl.Call(m, "MatchAny", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// MatchAny indicates an expected call of MatchAny
func (mr *MockRegexpRepositoryMockRecorder) MatchAny(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchAny", reflect.TypeOf((*MockRegexpRepository)(nil).MatchAny), arg0)
}

// MockPathMatcherRepository is a mock of PathMatcherRepository interface
type MockPathMatcherRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPathMatcherRepositoryMockRecorder
}

// MockPathMatcherRepositoryMockRecorder is the mock recorder for MockPathMatcherRepository
type MockPathMatcherRepositoryMockRecorder struct {
	mock *MockPathMatcherRepository
}

// NewMockPathMatcherRepository creates a new mock instance
func NewMockPathMatcherRepository(ctrl *gomock.Controller) *MockPathMatcherRepository {
	mock := &MockPathMatcherRepository{ctrl: ctrl}
	mock.recorder = &MockPathMatcherRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPathMatcherRepository) EXPECT() *MockPathMatcherRepositoryMockRecorder {
	return m.recorder
}

// Match mocks base method
func (m *MockPathMatcherRepository) Match(arg0 string) bool {
	ret := m.ctrl.Call(m, "Match", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Match indicates an expected call of Match
func (mr *MockPathMatcherRepositoryMockRecorder) Match(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Match", reflect.TypeOf((*MockPathMatcherRepository)(nil).Match), arg0)
}

// Prepare mocks base method
func (m *MockPathMatcherRepository) Prepare(arg0 generator.OptionFlagEntiry) error {
	ret := m.ctrl.Call(m, "Prepare", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Prepare indicates an expected call of Prepare
func (mr *MockPathMatcherRepositoryMockRecorder) Prepare(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockPathMatcherRepository)(nil).Prepare), arg0)
}
